name: pre_gnn
params:
  proteins:
    gat:
      epochs: 1200
      eval_steps: 50
      warmup_ratio: 0.0

      finetune_prefix: 'null'
      out_dir: './huggingface_logs'
      ckpt: '~/model/'
      gnn_grad_acc: false
      save_model: true

      lr: 0.002
      lr_scale: 0.0
      weight_decay: 0.0
      decay_scale: 0.0

    MLP:
      epochs: 200
      eval_steps: 100
      warmup_ratio: 0.0

      finetune_prefix: 'null'
      out_dir: './huggingface_logs'
      ckpt: '~/model/'
      gnn_grad_acc: false
      save_model: false

      lr: 0.01
      lr_scale: 0.0
      weight_decay: 0.0
      decay_scale: 0.0
